name: HaskellNixCabalStarter
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base
- scotty
executables:
  app:
    source-dirs: src
    main: Main.hs
default-extensions: 
- LambdaCase
